import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Light mode colors from Stitch
        "on-primary-fixed": "#0f0069",
        "surface-tint": "#4d44e3",
        "surface-dim": "#cbdbf5",
        "surface-container-high": "#dce9ff",
        "secondary-fixed": "#dae2fd",
        "tertiary-container": "#a44100",
        "surface-variant": "#d3e4fe",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#bec6e0",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#3f465c",
        "tertiary": "#7e3000",
        "outline-variant": "#c7c4d8",
        "primary": "#3525cd",
        "surface-container": "#e5eeff",
        "on-tertiary-container": "#ffd2be",
        "background": "#f8f9ff",
        "surface": "#f8f9ff",
        "on-tertiary-fixed-variant": "#7b2f00",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#ffb695",
        "on-primary-container": "#dad7ff",
        "primary-fixed": "#e2dfff",
        "surface-bright": "#f8f9ff",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#213145",
        "secondary": "#565e74",
        "tertiary-fixed": "#ffdbcc",
        "error-container": "#ffdad6",
        "on-surface": "#0b1c30",
        "primary-container": "#4f46e5",
        "on-background": "#0b1c30",
        "surface-container-highest": "#d3e4fe",
        "inverse-on-surface": "#eaf1ff",
        "on-secondary": "#ffffff",
        "surface-container-low": "#eff4ff",
        "outline": "#777587",
        "primary-fixed-dim": "#c3c0ff",
        "on-error": "#ffffff",
        "on-secondary-container": "#5c647a",
        "secondary-container": "#dae2fd",
        "inverse-primary": "#c3c0ff",
        "on-secondary-fixed": "#131b2e",
        "on-surface-variant": "#464555",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#3323cc",
        "on-tertiary-fixed": "#351000",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "16px",
        "container-max": "1280px",
        sm: "8px",
        base: "4px",
        md: "16px",
        "2xl": "48px",
        lg: "24px",
        xs: "4px",
        xl: "32px",
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "headline-sm": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "label-md": ["Geist", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "label-sm": ["Geist", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-sm": [
          "20px",
          { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "headline-lg": [
          "30px",
          { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "headline-md": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" },
        ],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "32px", fontWeight: "600" },
        ],
        "label-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" },
        ],
      },
    },
  },
  plugins: [],
};
export default config;